name: Atualizar Fundamentus

on:
  # Rodar todo dia útil às 10h da manhã (UTC)
  schedule:
    - cron: "0 13 * * 1-5"
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Rodar scraping
        run: python scraping_fundamentus.py

      - name: Commit JSON atualizado
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.json
          git commit -m "Atualiza dados Fundamentus"
          git push
